### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by Marcono1234** [jenkinsci/bridge-method-injector#28]
Hello,
would it be possible to add a README to this project, which explains the project and how to use it a bit? Currently for new users this might not be immediately obvious, and they might not spot the link to the website on the right sidebar.
Additionally the link http://bridge-method-injector.infradna.com/ seems to be dead (but at least [an old version has been archived](https://web.archive.org/web/20180818064629/https://bridge-method-injector.infradna.com/)).

**Comment by basil** [comment]
Fixed in commit 8a5b5e9.
